package com.pscsw.dao;

import com.pscsw.po.StudentReport;

public interface StudentReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbg.generated Wed Jun 28 07:43:15 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbg.generated Wed Jun 28 07:43:15 CST 2023
     */
    int insert(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbg.generated Wed Jun 28 07:43:15 CST 2023
     */
    int insertSelective(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbg.generated Wed Jun 28 07:43:15 CST 2023
     */
    StudentReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbg.generated Wed Jun 28 07:43:15 CST 2023
     */
    int updateByPrimaryKeySelective(StudentReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_report
     *
     * @mbg.generated Wed Jun 28 07:43:15 CST 2023
     */
    int updateByPrimaryKey(StudentReport record);
}